/**
 * SAFE-PROFESSIONAL-XLSX-EXPORT-A
 *
 * Tests for the new multi-sheet "Availability Export" workbook builder
 * (buildAvailabilityExportWorkbook/exportAvailabilityXlsx) added to
 * src/shared/lib/professional-export.ts, which replaces StatusCenterScreen's
 * ad-hoc CSV export with a real, styled `.xlsx`.
 *
 * Run: npm test -- --run export
 */
import { describe, it, expect } from 'vitest';
import { readFileSync } from 'fs';
import { join } from 'path';
import ExcelJS from 'exceljs';
import {
  buildAvailabilityExportWorkbook,
  exportAvailabilityXlsx,
  type AvailabilityExportRow,
  type AvailabilityExportConfig,
} from '@/shared/lib/professional-export';

const SRC = join(__dirname, '../../../');
const moduleSrc = readFileSync(join(SRC, 'shared/lib/professional-export.ts'), 'utf8');

const CONDITION_LABELS: Record<string, string> = {
  available: 'Available / متوفر',
  low_stock: 'Low Stock / منخفض',
  missing: 'Missing / مفقود',
  surplus: 'Surplus / فائض',
  near_expiry: 'Near Expiry / قريب الانتهاء',
  expired: 'Expired / منتهي الصلاحية',
};

function row(overrides: Partial<AvailabilityExportRow> = {}): AvailabilityExportRow {
  return {
    no: 1,
    institution: 'Test Hospital',
    outlet: 'Main Pharmacy',
    scientificName: 'Paracetamol',
    tradeName: 'Panadol',
    dosageForm: 'Tablet',
    concentration: '500mg',
    batchNumber: 'B123',
    quantity: 40,
    conditionKey: 'available',
    conditionLabel: CONDITION_LABELS.available,
    expiryDate: new Date('2027-01-01'),
    daysToExpiry: 200,
    expiryRiskLabel: 'Normal / طبيعي',
    lastUpdatedBy: 'Dr. Ahmed',
    lastUpdatedAt: new Date('2026-06-01T10:00:00Z'),
    notes: 'Some note',
    ...overrides,
  };
}

function baseConfig(overrides: Partial<AvailabilityExportConfig> = {}): AvailabilityExportConfig {
  return {
    reportTitle: 'Live Availability Status Report',
    moduleName: 'Status Center',
    generatedAt: new Date('2026-06-01T12:00:00Z'),
    lang: 'en',
    fileNameBase: 'medistock-status-test',
    filtersSummary: 'All',
    footerText: 'Generated by MediStock Phoenix',
    emptyMessage: 'No records',
    conditionLabels: CONDITION_LABELS,
    rows: [row()],
    ...overrides,
  };
}

describe('buildAvailabilityExportWorkbook: workbook structure', () => {
  it('produces exactly 3 sheets named Summary, Availability Export, Data Dictionary (in that order)', async () => {
    const wb = await buildAvailabilityExportWorkbook(baseConfig());
    const names = wb.worksheets.map(ws => ws.name);
    expect(names).toEqual(['Summary', 'Availability Export', 'Data Dictionary']);
  });

  it('sets workbook Creator/Created/Modified metadata', async () => {
    const wb = await buildAvailabilityExportWorkbook(baseConfig());
    expect(wb.creator).toBe('MediStock Phoenix');
    expect(wb.created).toBeInstanceOf(Date);
    expect(wb.modified).toBeInstanceOf(Date);
  });

  it('sets RTL worksheet view for Arabic, LTR for English', async () => {
    const wbEn = await buildAvailabilityExportWorkbook(baseConfig({ lang: 'en' }));
    const wbAr = await buildAvailabilityExportWorkbook(baseConfig({ lang: 'ar' }));
    for (const ws of wbEn.worksheets) expect(ws.views?.[0]?.rightToLeft).toBe(false);
    for (const ws of wbAr.worksheets) expect(ws.views?.[0]?.rightToLeft).toBe(true);
  });
});

describe('Availability Export sheet: bilingual headers', () => {
  it('every column header contains both an English and an Arabic label, exactly matching the required field list', async () => {
    const wb = await buildAvailabilityExportWorkbook(baseConfig());
    const ws = wb.getWorksheet('Availability Export')!;
    // Header row is the first row whose first cell equals the No. header.
    let headerRow: ExcelJS.Row | undefined;
    ws.eachRow(r => { if (String(r.getCell(1).value).startsWith('No.')) headerRow = r; });
    expect(headerRow).toBeDefined();
    const headers = (headerRow!.values as unknown[]).slice(1).map(String);
    const expected = [
      'No. / الرقم', 'Institution / المؤسسة', 'Outlet / المنفذ',
      'Scientific Name / الاسم العلمي', 'Trade Name / الاسم التجاري',
      'Dosage Form / الشكل', 'Concentration / التركيز', 'Batch No. / رقم الوجبة',
      'Quantity / الكمية', 'Condition / الحالة', 'Expiry Date / تاريخ النفاد',
      'Days to Expiry / أيام النفاد', 'Expiry Risk / خطورة النفاد',
      'Last Updated By / آخر محدث', 'Last Updated At / وقت التحديث', 'Notes / ملاحظات',
    ];
    expect(headers).toEqual(expected);
  });

  it('header row is bold, teal-filled, and centered/wrapped', async () => {
    const wb = await buildAvailabilityExportWorkbook(baseConfig());
    const ws = wb.getWorksheet('Availability Export')!;
    let headerRow: ExcelJS.Row | undefined;
    ws.eachRow(r => { if (String(r.getCell(1).value).startsWith('No.')) headerRow = r; });
    const cell = headerRow!.getCell(1);
    expect(cell.font?.bold).toBe(true);
    expect((cell.fill as ExcelJS.FillPattern).fgColor?.argb).toBe('FF0D9488');
    expect(cell.alignment?.wrapText).toBe(true);
  });
});

describe('Availability Export sheet: data rows, dates, and condition-based styling', () => {
  it('writes one data row per input row, with the correct field values', async () => {
    const wb = await buildAvailabilityExportWorkbook(baseConfig({ rows: [row({ scientificName: 'Amoxicillin', quantity: 12 })] }));
    const ws = wb.getWorksheet('Availability Export')!;
    let dataRow: ExcelJS.Row | undefined;
    ws.eachRow(r => { if (r.getCell(4).value === 'Amoxicillin') dataRow = r; });
    expect(dataRow).toBeDefined();
    expect(dataRow!.getCell(9).value).toBe(12);
  });

  it('expiryDate/lastUpdatedAt cells are real Date values with yyyy-mm-dd / yyyy-mm-dd hh:mm numFmt', async () => {
    const wb = await buildAvailabilityExportWorkbook(baseConfig());
    const ws = wb.getWorksheet('Availability Export')!;
    let dataRow: ExcelJS.Row | undefined;
    ws.eachRow(r => { if (r.getCell(4).value === 'Paracetamol') dataRow = r; });
    const expiryCell = dataRow!.getCell(11);
    const updatedCell = dataRow!.getCell(15);
    expect(expiryCell.value).toBeInstanceOf(Date);
    expect(expiryCell.numFmt).toBe('yyyy-mm-dd');
    expect(updatedCell.value).toBeInstanceOf(Date);
    expect(updatedCell.numFmt).toBe('yyyy-mm-dd hh:mm');
  });

  it('a null expiryDate/lastUpdatedAt renders as "—", never "Invalid Date"', async () => {
    const wb = await buildAvailabilityExportWorkbook(baseConfig({ rows: [row({ expiryDate: null, lastUpdatedAt: null })] }));
    const ws = wb.getWorksheet('Availability Export')!;
    let dataRow: ExcelJS.Row | undefined;
    ws.eachRow(r => { if (r.getCell(4).value === 'Paracetamol') dataRow = r; });
    expect(dataRow!.getCell(11).value).toBe('—');
    expect(dataRow!.getCell(15).value).toBe('—');
    expect(String(dataRow!.getCell(11).value)).not.toContain('Invalid Date');
  });

  it('a "missing" row gets a red fill and bold red condition text; an "available" row gets a green/neutral fill', async () => {
    const wb = await buildAvailabilityExportWorkbook(baseConfig({
      rows: [
        row({ scientificName: 'MissingDrug', conditionKey: 'missing', conditionLabel: CONDITION_LABELS.missing }),
        row({ scientificName: 'OkDrug', conditionKey: 'available', conditionLabel: CONDITION_LABELS.available }),
      ],
    }));
    const ws = wb.getWorksheet('Availability Export')!;
    let missingRow: ExcelJS.Row | undefined;
    let okRow: ExcelJS.Row | undefined;
    ws.eachRow(r => {
      if (r.getCell(4).value === 'MissingDrug') missingRow = r;
      if (r.getCell(4).value === 'OkDrug') okRow = r;
    });
    const missingFill = (missingRow!.getCell(4).fill as ExcelJS.FillPattern).fgColor?.argb;
    const okFill = (okRow!.getCell(4).fill as ExcelJS.FillPattern).fgColor?.argb;
    expect(missingFill).toBe('FFFCE8E8');
    expect(okFill).toBe('FFF1FBF5');
    const missingConditionCell = missingRow!.getCell(10);
    expect(missingConditionCell.font?.bold).toBe(true);
    expect(missingConditionCell.font?.color?.argb).toBe('FF991B1B');
  });

  it('shows the empty-state message and no data rows when rows is empty', async () => {
    const wb = await buildAvailabilityExportWorkbook(baseConfig({ rows: [], emptyMessage: 'No records' }));
    const ws = wb.getWorksheet('Availability Export')!;
    let found = false;
    ws.eachRow(r => { if (r.getCell(1).value === 'No records') found = true; });
    expect(found).toBe(true);
  });

  it('adds an autoFilter and a frozen header row when there is at least one row', async () => {
    const wb = await buildAvailabilityExportWorkbook(baseConfig());
    const ws = wb.getWorksheet('Availability Export')!;
    expect(ws.autoFilter).toBeDefined();
    expect(ws.views?.[0]?.state).toBe('frozen');
  });
});

describe('Summary sheet: totals by condition', () => {
  it('counts rows per conditionKey and lists them in conditionLabels order', async () => {
    const wb = await buildAvailabilityExportWorkbook(baseConfig({
      rows: [
        row({ conditionKey: 'missing' }),
        row({ conditionKey: 'missing' }),
        row({ conditionKey: 'available' }),
      ],
    }));
    const ws = wb.getWorksheet('Summary')!;
    const values: Record<string, number> = {};
    ws.eachRow(r => {
      const label = String(r.getCell(1).value);
      if (Object.values(CONDITION_LABELS).includes(label)) {
        values[label] = Number(r.getCell(2).value);
      }
    });
    expect(values[CONDITION_LABELS.missing]).toBe(2);
    expect(values[CONDITION_LABELS.available]).toBe(1);
    expect(values[CONDITION_LABELS.low_stock]).toBe(0);
  });

  it('includes generated-at, filters, and total-rows meta lines', async () => {
    const wb = await buildAvailabilityExportWorkbook(baseConfig({ filtersSummary: 'Status: Missing', rows: [row(), row()] }));
    const ws = wb.getWorksheet('Summary')!;
    const cellTexts: string[] = [];
    ws.eachRow(r => cellTexts.push(String(r.getCell(2).value ?? '')));
    expect(cellTexts).toContain('Status: Missing');
    expect(cellTexts).toContain('2');
  });
});

describe('Data Dictionary sheet', () => {
  it('has a Field / Description header row and one entry per Availability Export column, plus a scope note', async () => {
    const wb = await buildAvailabilityExportWorkbook(baseConfig());
    const ws = wb.getWorksheet('Data Dictionary')!;
    let headerRow: ExcelJS.Row | undefined;
    ws.eachRow(r => { if (String(r.getCell(1).value).includes('Field')) headerRow = r; });
    expect(headerRow).toBeDefined();
    expect(String(headerRow!.getCell(1).value)).toContain('الحقل');
    expect(String(headerRow!.getCell(2).value)).toContain('الوصف');

    const fieldNames: string[] = [];
    ws.eachRow(r => fieldNames.push(String(r.getCell(1).value)));
    for (const label of ['No. / الرقم', 'Institution / المؤسسة', 'Notes / ملاحظات']) {
      expect(fieldNames).toContain(label);
    }
  });

  it('mentions that removed materials are excluded from the export scope', async () => {
    const wb = await buildAvailabilityExportWorkbook(baseConfig());
    const ws = wb.getWorksheet('Data Dictionary')!;
    let scopeDescription = '';
    ws.eachRow(r => {
      if (String(r.getCell(1).value).startsWith('Scope')) scopeDescription = String(r.getCell(2).value);
    });
    expect(scopeDescription).toMatch(/removed_at/);
  });
});

describe('exportAvailabilityXlsx', () => {
  it('is exported as an async function returning a boolean', () => {
    expect(typeof exportAvailabilityXlsx).toBe('function');
  });
});

describe('Static source guards: no sensitive fields, additive only', () => {
  it('AVAIL_EXPORT_COLUMNS never includes an id/uuid/removed_by/auth-id-like column key', () => {
    const block = moduleSrc.slice(moduleSrc.indexOf('const AVAIL_EXPORT_COLUMNS'), moduleSrc.indexOf('function availExportCellValue'));
    expect(block).not.toMatch(/key:\s*'id'/);
    expect(block).not.toMatch(/removed_by/);
    expect(block).not.toMatch(/organization_id|distribution_point_id/);
  });

  it('AvailabilityExportRow type has no id/removed_by/organization_id/auth-id fields', () => {
    const block = moduleSrc.slice(moduleSrc.indexOf('export interface AvailabilityExportRow'), moduleSrc.indexOf('export interface AvailabilityExportConfig'));
    expect(block).not.toMatch(/\bid:\s*string/);
    expect(block).not.toMatch(/removed_by/);
    expect(block).not.toMatch(/organization_id|distribution_point_id/);
  });

  it('this addition does not modify buildProfessionalWorkbook/exportProfessionalXlsx/exportProfessionalCsv (still present, unrenamed)', () => {
    expect(moduleSrc).toContain('export async function buildProfessionalWorkbook');
    expect(moduleSrc).toContain('export async function exportProfessionalXlsx');
    expect(moduleSrc).toContain('export function exportProfessionalCsv');
  });
});
