/**
 * EXPORT-PROFESSIONAL-XLSX-PDF-A / EXPORT-PROFESSIONAL-XLSX-PDF-B / EXPORT-XLSX-DYNAMIC-IMPORT-A
 *
 * Tests for the shared professional export config layer
 * (src/shared/lib/professional-export.ts).
 *
 * EXPORT-PROFESSIONAL-XLSX-PDF-B: the user explicitly required real Excel
 * export, not CSV. `exceljs` is now an approved, installed dependency (see
 * package.json) and `exportProfessionalXlsx`/`buildProfessionalWorkbook` are
 * the PRIMARY "Excel export" path, producing a true `.xlsx` workbook
 * (Creator/Created/Modified metadata, RTL worksheet view, frozen header,
 * auto-filter, styled header/alternating rows, real Date cells with explicit
 * numFmt so dates can never render as `###`). `exportProfessionalCsv` is
 * kept only as an explicitly-marked legacy/optional fallback, not wired to
 * any screen. PDF/print still uses the existing dependency-free browser
 * print-to-PDF path (no PDF library was added — jsPDF/pdfmake/pdf-lib are
 * out of scope for this phase).
 *
 * EXPORT-XLSX-DYNAMIC-IMPORT-A: ExcelJS is no longer a top-level static
 * import in professional-export.ts (that would bundle its ~900KB into the
 * app's main chunk, loaded on every visit even though export is rarely
 * used). It's now loaded via a lazy `import('exceljs')` inside
 * `buildProfessionalWorkbook`, which is therefore now async — every test
 * below that calls it awaits the result. This test file itself imports
 * ExcelJS statically because it's test-only code (never shipped in the app
 * bundle), so it can use `ExcelJS.Workbook`/`ExcelJS.Row`/etc. as before.
 *
 * Run: npm test -- --run
 */
import { describe, it, expect } from 'vitest';
import { readFileSync } from 'fs';
import { join } from 'path';
import ExcelJS from 'exceljs';
import {
  exportProfessionalXlsx,
  exportProfessionalMultiSheetXlsx,
  buildProfessionalWorkbook,
  buildMultiSheetProfessionalWorkbook,
  buildPremiumPrintHtml,
  sanitizeReportColumns,
  neutralizeFormulaValue,
  formatExportDateCell,
  formatExportDateText,
  type ProfessionalReportColumn,
  type ProfessionalExportConfig,
} from '@/shared/lib/professional-export';

const SRC = join(__dirname, '../../../');
const ROOT = join(__dirname, '../../../../');
const read = (rel: string) => readFileSync(join(SRC, rel), 'utf8');
const moduleSrc = read('shared/lib/professional-export.ts');

interface Row { id: string; uuid?: string; name: string; qty: number; when: string | Date | null; status: 'missing' | 'available'; }

function baseConfig(overrides: Partial<ProfessionalExportConfig<Row>> = {}): ProfessionalExportConfig<Row> {
  const columns: ProfessionalReportColumn<Row>[] = [
    { key: 'name', label: 'Name', value: r => r.name },
    { key: 'qty', label: 'Qty', value: r => String(r.qty), numeric: true, excelValue: r => r.qty },
    { key: 'when', label: 'When', value: r => String(r.when ?? '—'), ltr: true },
  ];
  return {
    reportTitle: 'Inventory Report',
    moduleName: 'Status Editor',
    generatedAt: new Date('2026-07-04T10:30:00'),
    filtersSummary: 'All',
    columns,
    rows: [{ id: 'row-1', name: 'Paracetamol', qty: 5, when: '2026-07-01', status: 'available' }],
    lang: 'en',
    fileNameBase: 'medistock-report',
    footerText: 'Generated by MediStock Phoenix',
    labels: { generatedAt: 'Generated at', filtersSummary: 'Filters', rowCount: 'Rows' },
    ...overrides,
  };
}

describe('approved scope: exceljs is installed and used; no PDF-generation dependency added', () => {
  it('package.json declares exceljs as a dependency', () => {
    const pkg = readFileSync(join(ROOT, 'package.json'), 'utf8');
    expect(pkg).toMatch(/"exceljs":\s*"\^?[\d.]+"/);
  });

  it('package.json has no jsPDF/pdfmake/pdf-lib/sheetjs dependency (only exceljs was approved)', () => {
    const pkg = readFileSync(join(ROOT, 'package.json'), 'utf8');
    expect(pkg).not.toMatch(/"jspdf"|"pdfmake"|"pdf-lib"|"read-excel-file"|"sheetjs"/i);
  });

  it('the module lazily imports ExcelJS (dynamic import, not a top-level static import) so it code-splits out of the main bundle', () => {
    expect(moduleSrc).toContain("import type ExcelJS from 'exceljs'");
    expect(moduleSrc).not.toMatch(/^import ExcelJS from 'exceljs';/m);
    expect(moduleSrc).toContain("import('exceljs')");
  });
});

describe('buildProfessionalWorkbook: real workbook, not CSV', () => {
  it('returns a genuine ExcelJS.Workbook instance with a worksheet', async () => {
    const wb = await buildProfessionalWorkbook(baseConfig());
    expect(wb).toBeInstanceOf(ExcelJS.Workbook);
    expect(wb.worksheets.length).toBe(1);
  });

  it('sets workbook Creator/Created/Modified metadata', async () => {
    const generatedAt = new Date('2026-07-04T10:30:00');
    const wb = await buildProfessionalWorkbook(baseConfig({ generatedAt }));
    expect(wb.creator).toBe('MediStock Phoenix');
    expect(wb.created).toEqual(generatedAt);
    expect(wb.modified).toEqual(generatedAt);
  });

  it('uses a safe worksheet name derived from the module/report title', async () => {
    const wb = await buildProfessionalWorkbook(baseConfig({ moduleName: 'Status: Editor / Report?' }));
    const name = wb.worksheets[0].name;
    expect(name).not.toMatch(/[:\\/?*[\]]/);
    expect(name.length).toBeLessThanOrEqual(31);
  });

  it('sets RTL worksheet view when lang is ar', async () => {
    const wbAr = await buildProfessionalWorkbook(baseConfig({ lang: 'ar' }));
    const wbEn = await buildProfessionalWorkbook(baseConfig({ lang: 'en' }));
    expect(wbAr.worksheets[0].views.some(v => v.rightToLeft === true)).toBe(true);
    expect(wbEn.worksheets[0].views.some(v => v.rightToLeft === true)).toBe(false);
  });

  it('includes a metadata section: report title, module name, generated-at, filters, row count', async () => {
    const wb = await buildProfessionalWorkbook(baseConfig());
    const ws = wb.worksheets[0];
    const cellTexts: string[] = [];
    ws.eachRow(row => row.eachCell(cell => cellTexts.push(String(cell.value ?? ''))));
    const joined = cellTexts.join(' | ');
    expect(joined).toContain('Inventory Report');
    expect(joined).toContain('Status Editor');
    expect(joined).toContain('Generated at');
    expect(joined).toContain('Filters');
    expect(joined).toContain('Rows');
  });

  it('styles the header row with a bold font and a solid brand fill', async () => {
    const wb = await buildProfessionalWorkbook(baseConfig());
    const ws = wb.worksheets[0];
    let headerRow: ExcelJS.Row | undefined;
    ws.eachRow(row => {
      if (row.getCell(1).value === 'Name') headerRow = row;
    });
    expect(headerRow).toBeDefined();
    const cell = headerRow!.getCell(1);
    expect(cell.font?.bold).toBe(true);
    expect(cell.fill && (cell.fill as ExcelJS.FillPattern).fgColor?.argb).toMatch(/^FF/);
  });

  it('freezes the pane at the header row', async () => {
    const wb = await buildProfessionalWorkbook(baseConfig());
    const ws = wb.worksheets[0];
    const frozenView = ws.views.find(v => v.state === 'frozen');
    expect(frozenView).toBeDefined();
    expect((frozenView as ExcelJS.WorksheetViewFrozen).ySplit).toBeGreaterThan(0);
  });

  it('sets an auto-filter range covering the header row through the last data row', async () => {
    const wb = await buildProfessionalWorkbook(baseConfig());
    const ws = wb.worksheets[0];
    expect(ws.autoFilter).toBeDefined();
    const af = ws.autoFilter as { from: { row: number; column: number }; to: { row: number; column: number } };
    expect(af.to.row).toBeGreaterThan(af.from.row);
    expect(af.to.column).toBe(3); // 3 columns in baseConfig
  });

  it('sets column widths wide enough that a date column can never render as "###" (>=16, datetime >=20)', async () => {
    const dateCols: ProfessionalReportColumn<Row>[] = [
      { key: 'when', label: 'When', value: r => String(r.when ?? '—'), dateColumn: 'date', excelValue: r => r.when ?? null },
      { key: 'ts', label: 'Timestamp', value: r => String(r.when ?? '—'), dateColumn: 'datetime', excelValue: r => r.when ?? null },
    ];
    const wb = await buildProfessionalWorkbook(baseConfig({ columns: dateCols }));
    const ws = wb.worksheets[0];
    expect(ws.getColumn('when').width).toBeGreaterThanOrEqual(16);
    expect(ws.getColumn('ts').width).toBeGreaterThanOrEqual(20);
  });
});

describe('date-safe handling (ISO string / Date object / date-only string / null / undefined / invalid)', () => {
  it('formatExportDateCell converts valid inputs to a real Date, and returns null for null/undefined/invalid', () => {
    expect(formatExportDateCell('2026-07-01T00:00:00.000Z')).toBeInstanceOf(Date);
    expect(formatExportDateCell(new Date('2026-07-02'))).toBeInstanceOf(Date);
    expect(formatExportDateCell('2026-07-03')).toBeInstanceOf(Date);
    expect(formatExportDateCell(null)).toBeNull();
    expect(formatExportDateCell(undefined)).toBeNull();
    expect(formatExportDateCell('not-a-real-date')).toBeNull();
  });

  it('formatExportDateText never renders "Invalid Date" for any input', () => {
    for (const v of ['2026-07-01', new Date('2026-07-02'), null, undefined, 'garbage' as unknown as string]) {
      expect(formatExportDateText(v, 'en')).not.toMatch(/Invalid Date/i);
    }
  });

  it('a valid date column gets a real Date cell with an explicit numFmt (never "###", never plain unformatted text)', async () => {
    const columns: ProfessionalReportColumn<Row>[] = [
      { key: 'when', label: 'When', value: r => String(r.when ?? '—'), dateColumn: 'date', excelValue: r => r.when ?? null },
    ];
    const rows: Row[] = [{ id: '1', name: 'A', qty: 1, when: '2026-07-01T00:00:00.000Z', status: 'available' }];
    const wb = await buildProfessionalWorkbook(baseConfig({ columns, rows }));
    const ws = wb.worksheets[0];
    let dataCell: ExcelJS.Cell | undefined;
    ws.eachRow(row => {
      const c = row.getCell(1);
      if (c.value instanceof Date) dataCell = c;
    });
    expect(dataCell).toBeDefined();
    expect(dataCell!.numFmt).toBe('yyyy-mm-dd');
  });

  it('a null/undefined/invalid date value never produces "Invalid Date" and is rendered as a safe dash instead', async () => {
    const columns: ProfessionalReportColumn<Row>[] = [
      { key: 'when', label: 'When', value: () => '—', dateColumn: 'date', excelValue: r => r.when },
    ];
    const rows: Row[] = [
      { id: '1', name: 'Null', qty: 1, when: null, status: 'available' },
      { id: '2', name: 'Invalid', qty: 1, when: 'not-a-real-date', status: 'available' },
    ];
    const wb = await buildProfessionalWorkbook(baseConfig({ columns, rows }));
    const ws = wb.worksheets[0];
    const values: unknown[] = [];
    ws.eachRow(row => values.push(row.getCell(1).value));
    expect(values.some(v => typeof v === 'string' && /invalid date/i.test(v))).toBe(false);
    expect(values).toContain('—');
  });
});

describe('formula injection safety', () => {
  it.each(['=cmd|calc', '+1+1', '-1-1', '@import', '\tSUM(A1)'])('neutralizes value starting with a risky character: %s', v => {
    expect(neutralizeFormulaValue(v)).toBe(`'${v}`);
  });

  it('leaves ordinary and Arabic text unchanged', () => {
    expect(neutralizeFormulaValue('Paracetamol 500mg')).toBe('Paracetamol 500mg');
    expect(neutralizeFormulaValue('باراسيتامول')).toBe('باراسيتامول');
  });

  it('a formula-like text value is neutralized before it reaches the Excel cell', async () => {
    const columns: ProfessionalReportColumn<Row>[] = [{ key: 'name', label: 'Name', value: () => '=cmd|calc' }];
    const wb = await buildProfessionalWorkbook(baseConfig({ columns }));
    const ws = wb.worksheets[0];
    const values: unknown[] = [];
    ws.eachRow(row => values.push(row.getCell(1).value));
    expect(values).toContain("'=cmd|calc");
    expect(values).not.toContain('=cmd|calc');
  });
});

describe('raw UUID / internal id exclusion', () => {
  it('drops id/uuid/token/*_id-named columns unless allowRawIdColumns is true', () => {
    const columns: ProfessionalReportColumn<Row>[] = [
      { key: 'id', label: 'ID', value: r => r.id },
      { key: 'name', label: 'Name', value: r => r.name },
    ];
    expect(sanitizeReportColumns(columns).map(c => c.key)).toEqual(['name']);
    expect(sanitizeReportColumns(columns, true).map(c => c.key)).toEqual(['id', 'name']);
  });

  it('blanks out a cell value that is itself a raw UUID string, even under an innocuous column key', () => {
    const columns: ProfessionalReportColumn<Row>[] = [
      { key: 'reference', label: 'Reference', value: () => '3fa85f64-5717-4562-b3fc-2c963f66afa6' },
    ];
    expect(sanitizeReportColumns(columns)[0].value({ id: '1', name: '', qty: 0, when: null, status: 'available' })).toBe('—');
  });

  it('never appears in the built workbook for a config carrying an id column, unless explicitly allowed', async () => {
    const columns: ProfessionalReportColumn<Row>[] = [
      { key: 'id', label: 'ID', value: r => r.id },
      { key: 'name', label: 'Name', value: r => r.name },
    ];
    const rows: Row[] = [{ id: 'abc-internal-id-123', name: 'Visible Name', qty: 1, when: null, status: 'available' }];
    const wb = await buildProfessionalWorkbook(baseConfig({ columns, rows }));
    const ws = wb.worksheets[0];
    const values: unknown[] = [];
    ws.eachRow(row => row.eachCell(cell => values.push(cell.value)));
    expect(values).not.toContain('abc-internal-id-123');
    expect(values).toContain('Visible Name');
  });
});

describe('exportProfessionalXlsx: filename, MIME, filtered rows exported', () => {
  it('downloads with a .xlsx extension (never .csv)', () => {
    expect(moduleSrc).toContain("buildStableFileName(config.fileNameBase, 'xlsx')");
  });

  it('uses the correct OOXML spreadsheet MIME type', () => {
    expect(moduleSrc).toContain("'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'");
  });

  it('never throws in a DOM-less test env — resolves to false instead of crashing', async () => {
    await expect(exportProfessionalXlsx(baseConfig())).resolves.toBe(false);
  });

  it('exports exactly the rows passed in the config (the caller\'s currently-filtered rows), preserving order', async () => {
    const rows: Row[] = [
      { id: '1', name: 'Second', qty: 2, when: null, status: 'available' },
      { id: '2', name: 'First', qty: 1, when: null, status: 'missing' },
    ];
    const wb = await buildProfessionalWorkbook(baseConfig({ rows }));
    const ws = wb.worksheets[0];
    const names: string[] = [];
    ws.eachRow(row => {
      const v = row.getCell(1).value;
      if (v === 'Second' || v === 'First') names.push(v);
    });
    expect(names).toEqual(['Second', 'First']);
  });
});

describe('buildMultiSheetProfessionalWorkbook: parent + drill-down detail in one workbook', () => {
  interface DetailRow { id: string; parent: string; qty: number; }

  function detailConfig(overrides: Partial<ProfessionalExportConfig<DetailRow>> = {}): ProfessionalExportConfig<DetailRow> {
    const columns: ProfessionalReportColumn<DetailRow>[] = [
      { key: 'parent', label: 'Parent', value: r => r.parent, ltr: true },
      { key: 'qty', label: 'Qty', value: r => String(r.qty), numeric: true, excelValue: r => r.qty },
    ];
    return {
      reportTitle: 'Detail Report',
      moduleName: 'Detail',
      generatedAt: new Date('2026-07-04T10:30:00'),
      filtersSummary: 'All',
      columns,
      rows: [{ id: 'd-1', parent: 'ORD-1', qty: 3 }],
      lang: 'en',
      fileNameBase: 'medistock-detail',
      footerText: 'Generated by MediStock Phoenix',
      labels: { generatedAt: 'Generated at', filtersSummary: 'Filters', rowCount: 'Rows' },
      ...overrides,
    };
  }

  it('produces one workbook with one worksheet per config, in order', async () => {
    const wb = await buildMultiSheetProfessionalWorkbook([baseConfig({ moduleName: 'Orders' }), detailConfig({ moduleName: 'Lines' })]);
    expect(wb.worksheets.length).toBe(2);
    expect(wb.worksheets[0].name).toBe('Orders');
    expect(wb.worksheets[1].name).toBe('Lines');
  });

  it('each sheet carries its OWN rows — the parent sheet never leaks detail rows and vice versa', async () => {
    const wb = await buildMultiSheetProfessionalWorkbook([
      baseConfig({ moduleName: 'Orders', rows: [{ id: '1', name: 'ORD-1', qty: 1, when: null, status: 'available' }] }),
      detailConfig({ moduleName: 'Lines', rows: [{ id: 'd-1', parent: 'ORD-1', qty: 3 }, { id: 'd-2', parent: 'ORD-1', qty: 7 }] }),
    ]);
    const ordersValues: unknown[] = [];
    wb.worksheets[0].eachRow(row => ordersValues.push(row.getCell(1).value));
    const linesValues: unknown[] = [];
    wb.worksheets[1].eachRow(row => linesValues.push(row.getCell(1).value));
    expect(ordersValues.filter(v => v === 'ORD-1').length).toBe(1);
    expect(linesValues.filter(v => v === 'ORD-1').length).toBe(2);
  });

  it('a single-sheet buildProfessionalWorkbook and a one-config buildMultiSheetProfessionalWorkbook produce the same sheet name and row count', async () => {
    const cfg = baseConfig();
    const single = await buildProfessionalWorkbook(cfg);
    const multi = await buildMultiSheetProfessionalWorkbook([cfg]);
    expect(multi.worksheets.length).toBe(1);
    expect(multi.worksheets[0].name).toBe(single.worksheets[0].name);
    expect(multi.worksheets[0].rowCount).toBe(single.worksheets[0].rowCount);
  });

  it('exportProfessionalMultiSheetXlsx never throws in a DOM-less test env — resolves to false instead of crashing', async () => {
    await expect(exportProfessionalMultiSheetXlsx([baseConfig(), detailConfig()], 'medistock-full')).resolves.toBe(false);
  });

  it('exportProfessionalMultiSheetXlsx downloads with a .xlsx extension and the correct OOXML MIME type (same contract as the single-sheet export)', () => {
    expect(moduleSrc).toContain('export async function exportProfessionalMultiSheetXlsx');
    const fn = moduleSrc.slice(moduleSrc.indexOf('export async function exportProfessionalMultiSheetXlsx'));
    expect(fn).toContain("buildStableFileName(fileNameBase, 'xlsx')");
    expect(fn).toContain("'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'");
  });
});

describe('exportProfessionalCsv: legacy/optional fallback, not the primary export path', () => {
  it('is documented as @deprecated / legacy, not wired to any screen', () => {
    const idx = moduleSrc.indexOf('export function exportProfessionalCsv');
    const before = moduleSrc.slice(Math.max(0, idx - 500), idx);
    expect(before).toMatch(/@deprecated/i);
    expect(before).toMatch(/legacy/i);
  });

  it('exportProfessionalXlsx is documented as the PRIMARY export path', () => {
    const idx = moduleSrc.indexOf('export async function exportProfessionalXlsx');
    const before = moduleSrc.slice(Math.max(0, idx - 500), idx);
    expect(before).toMatch(/PRIMARY/);
  });
});

describe('buildPremiumPrintHtml: RTL/LTR, branding, metadata, date-safety, same rows as XLSX', () => {
  it('sets dir="rtl" for Arabic and dir="ltr" for English', () => {
    const ar = buildPremiumPrintHtml(baseConfig({ lang: 'ar' }));
    const en = buildPremiumPrintHtml(baseConfig({ lang: 'en' }));
    expect(ar).toContain('<html dir="rtl" lang="ar">');
    expect(en).toContain('<html dir="ltr" lang="en">');
  });

  it('includes report title, module name, brand, footer, and metadata lines', () => {
    const html = buildPremiumPrintHtml(baseConfig());
    expect(html).toContain('Inventory Report');
    expect(html).toContain('Status Editor');
    expect(html).toContain('Generated by MediStock Phoenix');
    expect(html).toContain('Generated at');
    expect(html).toContain('Filters');
    expect(html).toContain('Rows');
  });

  it('renders date columns as readable text, never "###" or "Invalid Date"', () => {
    const columns: ProfessionalReportColumn<Row>[] = [
      { key: 'when', label: 'When', value: r => String(r.when ?? '—'), dateColumn: 'date', excelValue: r => r.when ?? null, ltr: true },
    ];
    const rows: Row[] = [
      { id: '1', name: 'A', qty: 1, when: '2026-07-01T00:00:00.000Z', status: 'available' },
      { id: '2', name: 'B', qty: 1, when: null, status: 'available' },
      { id: '3', name: 'C', qty: 1, when: 'not-a-real-date', status: 'available' },
    ];
    const html = buildPremiumPrintHtml(baseConfig({ columns, rows }));
    expect(html).not.toContain('###');
    expect(html).not.toMatch(/Invalid Date/i);
    expect(html).toContain('2026-07-01');
  });

  it('styles a bold/colored table header and alternating row background', async () => {
    const html = buildPremiumPrintHtml(baseConfig());
    expect(html).toContain('th { background:');
    expect(html).toContain('font-weight: 700');
    expect(html).toContain('tbody tr:nth-child(even)');
  });

  it('escapes HTML-injection attempts in row values', () => {
    const html = buildPremiumPrintHtml(baseConfig({ rows: [{ id: '1', name: '<script>alert(1)</script>', qty: 1, when: null, status: 'available' }] }));
    expect(html).not.toContain('<script>alert');
    expect(html).toContain('&lt;script&gt;');
  });

  it('renders the translated empty-state message instead of an empty table when there are zero rows', () => {
    const html = buildPremiumPrintHtml(baseConfig({ rows: [], emptyMessage: 'No records' }));
    expect(html).toContain('No records');
    expect(html).not.toContain('<table>');
  });

  it('same config (same rows/columns) feeds both buildProfessionalWorkbook and buildPremiumPrintHtml — no divergent row set between XLSX and PDF', async () => {
    const config = baseConfig({ rows: [
      { id: '1', name: 'Alpha', qty: 1, when: null, status: 'available' },
      { id: '2', name: 'Beta', qty: 2, when: null, status: 'missing' },
    ] });
    const html = buildPremiumPrintHtml(config);
    const wb = await buildProfessionalWorkbook(config);
    const ws = wb.worksheets[0];
    const xlsxNames: string[] = [];
    ws.eachRow(row => {
      const v = row.getCell(1).value;
      if (v === 'Alpha' || v === 'Beta') xlsxNames.push(v);
    });
    expect(html).toContain('Alpha');
    expect(html).toContain('Beta');
    expect(xlsxNames).toEqual(['Alpha', 'Beta']);
  });
});

describe('triggerProfessionalPrint / MobilePrintFallbackModal safety (unchanged from EXPORT-PROFESSIONAL-XLSX-PDF-A)', () => {
  it('branches to mobileHtml without calling window.open when isLikelyMobilePrintContext() is true', () => {
    expect(moduleSrc).toContain('if (isLikelyMobilePrintContext())');
    expect(moduleSrc).toContain('return { ok: true, mobileHtml: html };');
  });
});

describe('Guards: no unrelated changes', () => {
  it('no inter_org_exchange / Service-D reference was added', () => {
    expect(moduleSrc).not.toMatch(/inter_org_exchange/i);
  });

  it('no service_role/auth.admin usage', () => {
    expect(moduleSrc).not.toMatch(/service_role|SUPABASE_SERVICE_ROLE|auth\.admin/i);
  });

  it('no WhatsApp/Graph API token strings', () => {
    expect(moduleSrc).not.toMatch(/graph\.facebook|WHATSAPP_TOKEN|whatsapp_business_api/i);
  });
});
